---
- name: Copy over current directory for repo build
  synchronize:
    src: ../../../../securedrop-firmware/
    dest: "{{ package_path }}"
    use_ssh_args: "{{ 'yes' if amazon_builder else omit }}"
    recursive: yes
    rsync_opts: "{{ securedrop-firmware_rsync_opts }}"

- name: Build securedrop-firmware deb package.
  command: dpkg-deb --build {{ package_path }}

- name: Fetch newly built deb packages back to localhost.
  fetch:
    src: "{{ package_path }}.deb"
    dest: "{{ securedrop-firmware_build_deb_package_local_dest_dir }}"
    flat: yes
    fail_on_missing: yes
